#服务信息
info:
    app:
        name: spring-boot-redis
        description: spring-boot-redis
        owner:
            - zuozmein
        emails:
            - badmeetevil@qq.com
        env: ${SPRING_PROFILES_ACTIVE}
        java-version: ${java.version}

#默认环境配置
server:
    port: 8082


#dev环境相关配置,覆盖上面的默认配置
---
spring:
    profiles: dev
# REDIS (RedisProperties)
# Redis服务器地址、端口、密码
redis:
    uri: redis://127.0.0.1:6379
# 连接池最大连接数（使用负值表示没有限制）、最大空闲连接
    pool:
        maxActive: 20
        maxWait: -1
        maxIdle: 8
        timeout: 0


#pub环境相关配置,覆盖上面的默认配置
---
spring:
    profiles: qa



#prod环境相关配置,覆盖上面的默认配置
---
spring:
    profiles: prod

